services:

  postgres:
    image: 'postgres:alpine3.22'
    container_name: video_postgres
    hostname: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      retries: 5
      start_period: 2s
      timeout: 3s

  backend:
    container_name: video_backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file: [.env]
    hostname: backend
    volumes:
      - ./data:/app/data
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy


volumes:
  db-data:
    driver: local